---
- name: HAProxy is installed
  yum:
    name: haproxy
    state: latest

- name: HAProxy is configured
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart HAproxy

- name: HAProxy is enabled and started
  service:
    name: haproxy
    state: started
    enabled: true

