---

- name: base setup
  hosts: all
  roles:
    - base

- name: setup tomcat
  hosts: apps
  roles:
    - tomcat


- name: Setup haproxy on frontends
  hosts: frontends
  roles:
    - haproxy

- name: Setup postgres
  hosts: appdbs
  roles:
    - postgres

