---
- name: Tomcat is installed
  yum:
    name: tomcat
    state: latest


- name: The ROOT app directory for tomcat exists
  file:
    path: /usr/share/tomcat/webapps/ROOT
    state: directory

- name: The ROOT app on tomcat has an index.html
  template:
    src: index.html.j2
    dest: "/usr/share/tomcat/webapps/ROOT/index.html"
    mode: 0644

- name: Tomcat is enabled and started
  service:
    name: tomcat
    enabled: yes
    state: started
